version: "3.9"  # wersja składni docker-compose

services:
  adguard:  # nazwa kontenera
    image: adguard/adguardhome
    container_name: adguard
    restart: unless-stopped   
    ports:
      - "53:53/udp"     
      - "80:80"
      - "3000:3000"             
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
